language: node_js

node_js:
  - stable

install:
  - npm install

script:
  - npm test

after_success: 
  - npm run coveralls

notifications:
  email:
    recipients:
      - oluwafemi.akinwa@andela.com
      - kaiser.phemi@protonmail.ch
      